### ISSUE TITLE
Update Add Either type and or_else from original Repo

### ISSUE THREAD

**Issue by julianbei** [ful-stackz/funky#3]
Two PRs got merged today:
- https://github.com/hqoss/monads/pull/77
- https://github.com/hqoss/monads/pull/77

It would be great if you could update this repo accordingly

**Comment by slavovojacek** [comment]
Thanks for the mention. Please note that the monads repo has just been updated with some much needed love.

I am trying to consolidate all projects under the HQOSS organisation so that all Node.js and Elixir projects can be scoped under `@hqoss`. As such, I'd recommend removing any mention of `@usefultools/monads` and soon `@usefultools/utils` as these are being moved under the new organisation on NPM.

I added the deprecation notice to https://www.npmjs.com/package/@usefultools/monads, and also a note to the project README. Please use `@hqoss/monads` going forward.

**Comment by ful-stackz** [comment]
Thank you both for the input, I greatly appreciate it!

@julianbei I am planning to and currently working on adding more functions to `Option` and `Result`. I will add the `Either` type as well!

@slavovojacek Thank you for letting me know about it! That is some VIP stuff right here - informing other people personally about deprecation 👼😃 I will update accordingly with the next release, which will hopefully be this weekend.
